"""
Generates tests/test_rubric.py from a rubric's test_suite.

Hint resolution order for each status:
  not_defined  -> hint_not_defined (fallback: hint_wrong_size)
  wrong_type   -> hint_wrong_type  (fallback: hint_wrong_size)
  wrong_size   -> hint_wrong_size
  nans         -> hint_nans        (fallback: hint_tolerance)
  tolerance    -> hint_tolerance

Each hint key can have a language-specific override by appending "_python",
e.g. "hint_wrong_size_python" overrides "hint_wrong_size" for Python only.
"""

HEADER = '''"""
Auto-generated by autobuilder from rubric.json.
Do not edit by hand -- re-run `autobuilder build` to regenerate.
"""
import unittest

from gradescope_utils.autograder_utils.decorators import number, weight

from autobuilder.comparator import compare
from autobuilder.inputs import convert_inputs, convert_value
from autobuilder.attempt_recorder import record as _record_attempt

import solution


class TestRubric(unittest.TestCase):
'''


def _is_python_test(t):
    return t.get("language", "python") == "python"


def _hint(t, key, fallback_key=None):
    """Return the most specific hint for key, with Python-suffix override."""
    python_key = key + "_python"
    val = t.get(python_key) or t.get(key, "")
    if not val and fallback_key:
        python_fallback = fallback_key + "_python"
        val = t.get(python_fallback) or t.get(fallback_key, "")
    return val


def _expected_expr(t):
    if "expected" in t:
        return f"convert_value({t['expected']!r})"
    ttype = t.get("type", "variable")
    if ttype == "variable":
        expr = f"solution.{t['variable_name']}"
    else:
        expr = f"solution.{t['function_name']}(*inputs)"
    if t.get("output_index") is not None:
        expr += f"[{t['output_index']!r}]"
    return expr


def _generate_test_method(t, index=0):
    name         = t["test_name"]
    score        = t.get("score", 0)
    description  = t.get("description", name)
    rtol         = t.get("rtol", 1e-6)
    atol         = t.get("atol", 1e-6)
    ttype        = t.get("type", "variable")

    # Resolve all hint variants
    h_not_defined = _hint(t, "hint_not_defined", "hint_wrong_size")
    h_wrong_type  = _hint(t, "hint_wrong_type",  "hint_wrong_size")
    h_wrong_size  = _hint(t, "hint_wrong_size")
    h_nans        = _hint(t, "hint_nans",        "hint_tolerance")
    h_tolerance   = _hint(t, "hint_tolerance")

    method_name = f"test_{index:04d}_{name}"

    lines = []
    lines.append(f"    @weight({score!r})")
    lines.append(f"    @number({name!r})")
    lines.append(f"    def {method_name}(self):")
    lines.append(f"        {description!r}")

    if ttype == "variable":
        varname = t["variable_name"]
        lines.append("        try:")
        lines.append(f"            from student_submission import {varname}")
        lines.append("        except Exception as e:")
        lines.append(f"            _record_attempt({name!r}, False)")
        lines.append(
            f"            self.fail(f\"Variable {varname!r} could not be loaded "
            f"({{type(e).__name__}}: {{e}}).\\nHint: \" + {h_not_defined!r})"
        )
        lines.append("            return")
        lines.append("")
        lines.append(f"        _record_attempt({name!r}, True)")
        lines.append(f"        result = {varname}")
    else:
        fname       = t["function_name"]
        inputs_repr = repr(t.get("inputs", []))
        lines.append("        try:")
        lines.append(f"            from student_submission import {fname}")
        lines.append("        except Exception as e:")
        lines.append(f"            _record_attempt({name!r}, False)")
        lines.append(
            f"            self.fail(f\"Function {fname!r} could not be loaded "
            f"({{type(e).__name__}}: {{e}}).\\nHint: \" + {h_not_defined!r})"
        )
        lines.append("            return")
        lines.append("")
        lines.append(f"        _record_attempt({name!r}, True)")
        lines.append(f"        inputs = convert_inputs({inputs_repr})")
        lines.append("        try:")
        lines.append(f"            result = {fname}(*inputs)")
        lines.append("        except Exception as e:")
        lines.append(
            f"            self.fail(f\"Your code raised an error when calling "
            f"{fname}(...): {{type(e).__name__}}: {{e}}\\nHint: \" + {h_not_defined!r})"
        )
        lines.append("            return")
        if t.get("output_index") is not None:
            lines.append(f"        result = result[{t['output_index']!r}]")

    lines.append(f"        expected = {_expected_expr(t)}")
    lines.append(f"        status, message = compare(result, expected, {rtol!r}, {atol!r})")
    lines.append('        if status == "wrong_type":')
    lines.append(f"            self.fail(message + \"\\nHint: \" + {h_wrong_type!r})")
    lines.append('        elif status == "wrong_size":')
    lines.append(f"            self.fail(message + \"\\nHint: \" + {h_wrong_size!r})")
    lines.append('        elif status == "nans":')
    lines.append(f"            self.fail(message + \"\\nHint: \" + {h_nans!r})")
    lines.append('        elif status == "tolerance":')
    lines.append(f"            self.fail(message + \"\\nHint: \" + {h_tolerance!r})")
    lines.append("")
    return "\n".join(lines)


def generate_test_file(test_suite):
    methods = []
    for i, t in enumerate(test_suite):
        if _is_python_test(t):
            methods.append(_generate_test_method(t, i))
    if not methods:
        methods.append("    pass")
    return HEADER + "\n".join(methods) + "\n"
