"""
Generates tests/test_rubric.py from a rubric's test_suite.

The generated file is a plain unittest.TestCase, one @weight-decorated
method per test_suite entry. Each method follows the
`try: from student_submission import X except Exception: ...` pattern,
then compares against either `solution.X` (or `solution.f(*inputs)`) or a
hardcoded "expected" value from the rubric.

The generated file is meant to be regenerated whenever rubric.json
changes -- it's not intended for hand-editing, though it's plain readable
unittest code if you need to look at what a given test does.
"""

HEADER = '''"""
Auto-generated by autobuilder from rubric.json.
Do not edit by hand -- re-run `autobuilder build` to regenerate.
"""
import unittest

from gradescope_utils.autograder_utils.decorators import number, weight

from autobuilder.comparator import compare
from autobuilder.inputs import convert_inputs, convert_value

import solution


class TestRubric(unittest.TestCase):
    # test_name -> bool, whether the variable/function was successfully
    # defined in this submission (regardless of correctness). Used by the
    # attempts feature (autobuilder/attempts.py) to track attempted
    # submissions across runs.
    ATTEMPT_STATUS = {}
'''


def _is_python_test(t):
    return t.get("language", "python") == "python"


def _expected_expr(t):
    if "expected" in t:
        return f"convert_value({t['expected']!r})"

    ttype = t.get("type", "variable")
    if ttype == "variable":
        expr = f"solution.{t['variable_name']}"
    else:
        expr = f"solution.{t['function_name']}(*inputs)"

    if t.get("output_index") is not None:
        expr += f"[{t['output_index']!r}]"
    return expr


def _generate_test_method(t):
    name = t["test_name"]
    score = t.get("score", 0)
    description = t.get("description", name)
    hint_wrong_size = t.get("hint_wrong_size", "")
    hint_tolerance = t.get("hint_tolerance", "")
    rtol = t.get("rtol", 1e-6)
    atol = t.get("atol", 1e-6)
    ttype = t.get("type", "variable")

    lines = []
    lines.append(f"    @weight({score!r})")
    lines.append(f"    @number({name!r})")
    lines.append(f"    def test_{name}(self):")
    lines.append(f"        {description!r}")

    if ttype == "variable":
        varname = t["variable_name"]
        lines.append("        try:")
        lines.append(f"            from student_submission import {varname}")
        lines.append("        except Exception as e:")
        lines.append(f"            TestRubric.ATTEMPT_STATUS[{name!r}] = False")
        lines.append(
            f"            self.fail(f\"Variable {varname!r} could not be "
            f"loaded ({{type(e).__name__}}: {{e}}).\\n\" + {hint_wrong_size!r})"
        )
        lines.append("            return")
        lines.append("")
        lines.append(f"        TestRubric.ATTEMPT_STATUS[{name!r}] = True")
        lines.append("        result = " + varname)

    else:  # function
        fname = t["function_name"]
        inputs_repr = repr(t.get("inputs", []))
        lines.append("        try:")
        lines.append(f"            from student_submission import {fname}")
        lines.append("        except Exception as e:")
        lines.append(f"            TestRubric.ATTEMPT_STATUS[{name!r}] = False")
        lines.append(
            f"            self.fail(f\"Function {fname!r} could not be "
            f"loaded ({{type(e).__name__}}: {{e}}).\\n\" + {hint_wrong_size!r})"
        )
        lines.append("            return")
        lines.append("")
        lines.append(f"        TestRubric.ATTEMPT_STATUS[{name!r}] = True")
        lines.append(f"        inputs = convert_inputs({inputs_repr})")
        lines.append("        try:")
        lines.append(f"            result = {fname}(*inputs)")
        lines.append("        except Exception as e:")
        lines.append(
            f"            self.fail(f\"Your code raised an error when calling "
            f"{fname}({{', '.join(repr(x) for x in inputs)}}): "
            f"{{type(e).__name__}}: {{e}}\\n\" + {hint_wrong_size!r})"
        )
        lines.append("            return")
        if t.get("output_index") is not None:
            lines.append(f"        result = result[{t['output_index']!r}]")

    lines.append(f"        expected = {_expected_expr(t)}")
    lines.append(f"        status, message = compare(result, expected, {rtol!r}, {atol!r})")
    lines.append('        if status == "shape":')
    lines.append(f"            self.fail(message + \"\\n\" + {hint_wrong_size!r})")
    lines.append('        elif status == "tolerance":')
    lines.append(f"            self.fail(message + \"\\n\" + {hint_tolerance!r})")
    lines.append("")
    return "\n".join(lines)


def generate_test_file(test_suite):
    methods = [_generate_test_method(t) for t in test_suite if _is_python_test(t)]
    if not methods:
        methods.append("    pass")
    return HEADER + "\n".join(methods) + "\n"
