"""
Generates tests/test_rubric.py from a rubric's test_suite.

Hint resolution order for each status:
  not_defined  -> hint_not_defined (fallback: hint_wrong_size)
  wrong_type   -> hint_wrong_type  (fallback: hint_wrong_size)
  wrong_size   -> hint_wrong_size
  nans         -> hint_nans        (fallback: hint_tolerance)
  tolerance    -> hint_tolerance

Each hint key can have a language-specific override by appending "_python",
e.g. "hint_wrong_size_python" overrides "hint_wrong_size" for Python only.
"""

HEADER = '''"""
Auto-generated by autobuilder from rubric.json.
Do not edit by hand -- re-run `autobuilder build` to regenerate.
"""
import unittest

from gradescope_utils.autograder_utils.decorators import number, weight

from autobuilder.comparator import compare
from autobuilder.inputs import convert_inputs, convert_value
from autobuilder.attempt_recorder import record as _record_attempt
from autobuilder.plot_check import extract_axes_info, compare_axes_info
from autobuilder.student_dispatch import get_student_result

import solution


class TestRubric(unittest.TestCase):
'''


def _hint(t, key, fallback_key=None):
    """Return the most specific hint for key, with Python-suffix override."""
    python_key = key + "_python"
    val = t.get(python_key) or t.get(key, "")
    if not val and fallback_key:
        python_fallback = fallback_key + "_python"
        val = t.get(python_fallback) or t.get(fallback_key, "")
    return val


def _hint_suffix_expr(hint_repr, image_md_repr=None):
    """Python expression for a '\\nHint: ...' suffix, optionally followed by
    an embedded image's markdown on its own line. Empty string if no hint
    and no image. Fully parenthesized so it's safe to concatenate with '+'."""
    parts = f"((\"\\nHint: \" + {hint_repr}) if {hint_repr} else \"\")"
    if image_md_repr:
        parts = f"({parts} + (\"\\n\\n\" + {image_md_repr}))"
    return parts


def _expected_expr(t):
    if "expected" in t:
        return f"convert_value({t['expected']!r})"
    ttype = t.get("type", "variable")
    if ttype == "variable":
        expr = f"solution.{t['variable_name']}"
    else:
        expr = f"solution.{t['function_name']}(*inputs)"
    if t.get("output_index") is not None:
        expr += f"[{t['output_index']!r}]"
    return expr


def _get_result_lines(t, name, h_not_defined):
    """Lines that fetch the student's value/function-call result via the
    language dispatcher, record the attempt, and bind the raw result to
    `result`. Shared by variable, function, and plot test types. Works
    identically regardless of whether the student submitted Python or
    Julia -- that's resolved at grading time by student_dispatch."""
    ttype = t.get("type", "variable")
    lines = []

    if ttype == "variable":
        varname = t["variable_name"]
        what = f"Variable {varname!r}"
        spec_repr = repr({"name": name, "type": "variable", "variable_name": varname})
    else:
        fname = t["function_name"]
        what = f"Function {fname!r}"
        inputs_repr = repr(t.get("inputs", []))
        spec_fields = {"name": name, "type": "function", "function_name": fname,
                       "inputs": t.get("inputs", [])}
        if t.get("output_index") is not None:
            spec_fields["output_index"] = t["output_index"]
        spec_repr = repr(spec_fields)

    lines.append(f"        _outcome = get_student_result({spec_repr})")
    lines.append('        if _outcome.get("missing"):')
    lines.append(f"            _record_attempt({name!r}, False)")
    lines.append(
        f"            detail = _outcome.get('error_detail')"
    )
    lines.append(
        f"            extra = f\" ({{detail.strip().splitlines()[-1]}})\" if detail else \"\""
    )
    lines.append(
        f"            self.fail(f\"{what} is not defined.\" + extra + "
        f"{_hint_suffix_expr(repr(h_not_defined))})"
    )
    lines.append("            return")
    lines.append('        if "call_error" in _outcome:')
    lines.append(f"            _record_attempt({name!r}, True)")

    if ttype == "variable":
        lines.append(
            f"            self.fail(f\"Your code raised an error reading {varname!r}: "
            f"{{_outcome['call_error'].strip().splitlines()[-1]}}\" + "
            f"{_hint_suffix_expr(repr(h_not_defined))})"
        )
    else:
        lines.append(
            f"            self.fail(f\"Your code raised an error when calling {fname!r}: "
            f"{{_outcome['call_error'].strip().splitlines()[-1]}}\" + "
            f"{_hint_suffix_expr(repr(h_not_defined))})"
        )
    lines.append("            return")
    lines.append("")
    lines.append(f"        _record_attempt({name!r}, True)")
    lines.append("        result = _outcome['value']")

    if ttype == "function" and t.get("inputs"):
        lines.append(f"        inputs = convert_inputs({repr(t.get('inputs', []))})")

    return lines


def _generate_plot_test_method(t, index=0):
    """Plot tests obtain a matplotlib Axes (directly, or via .axes on a
    Figure) the same way variable/function tests obtain their result, then
    compare structural properties (labels, limits, line/bar data) instead
    of comparing the object itself."""
    name        = t["test_name"]
    score       = t.get("score", 0)
    description = t.get("description", name)
    plot_checks = t.get("plot_checks", ["xlabel", "ylabel", "title", "n_lines", "line_data"])

    h_not_defined = _hint(t, "hint_not_defined", "hint_wrong_size")
    h_wrong_type  = _hint(t, "hint_wrong_type",  "hint_wrong_size")
    h_wrong_size  = _hint(t, "hint_wrong_size")
    h_nans        = _hint(t, "hint_nans",        "hint_tolerance")
    h_tolerance   = _hint(t, "hint_tolerance")
    image_md      = t.get("hint_image_md")
    image_md_repr = repr(image_md) if image_md else None

    method_name = f"test_{index:04d}_{name}"

    lines = []
    lines.append(f"    @weight({score!r})")
    lines.append(f"    @number({name!r})")
    lines.append(f"    def {method_name}(self):")
    lines.append(f"        {description!r}")
    lines.extend(_get_result_lines(t, name, h_not_defined))
    lines.append("")
    lines.append("        ax = result.axes[0] if hasattr(result, 'axes') and not hasattr(result, 'get_xlabel') else result")
    lines.append(f"        plot_checks = {plot_checks!r}")
    lines.append("        try:")
    lines.append("            student_info = extract_axes_info(ax, plot_checks)")
    lines.append("        except AttributeError as e:")
    lines.append(
        f"            self.fail(f\"Expected a matplotlib Axes (or a Figure with one Axes), "
        f"got {{type(ax).__name__}}: {{e}}.\" + {_hint_suffix_expr(repr(h_wrong_type))})"
    )
    lines.append("            return")
    lines.append("")
    if "expected" in t:
        lines.append(f"        ref_info = {t['expected']!r}")
    else:
        lines.append(f"        sol_ax_raw = {_solution_result_expr(t)}")
        lines.append("        sol_ax = sol_ax_raw.axes[0] if hasattr(sol_ax_raw, 'axes') and not hasattr(sol_ax_raw, 'get_xlabel') else sol_ax_raw")
        lines.append("        ref_info = extract_axes_info(sol_ax, plot_checks)")
    lines.append("        rtol_, atol_ = " + repr(t.get("rtol", 1e-2)) + ", " + repr(t.get("atol", 1e-2)))
    lines.append("        status, message = compare_axes_info(student_info, ref_info, rtol_, atol_)")
    lines.append('        if status == "wrong_type":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_wrong_type))})")
    lines.append('        elif status == "wrong_size":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_wrong_size))})")
    lines.append('        elif status == "nans":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_nans), image_md_repr)})")
    lines.append('        elif status == "tolerance":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_tolerance), image_md_repr)})")
    lines.append("")
    return "\n".join(lines)


def _solution_result_expr(t):
    ttype = t.get("type", "variable")
    if ttype == "variable":
        return f"solution.{t['variable_name']}"
    expr = f"solution.{t['function_name']}(*inputs)"
    return expr


def _generate_test_method(t, index=0):
    if t.get("type") == "plot":
        return _generate_plot_test_method(t, index)

    name         = t["test_name"]
    score        = t.get("score", 0)
    description  = t.get("description", name)
    rtol         = t.get("rtol", 1e-6)
    atol         = t.get("atol", 1e-6)

    # Resolve all hint variants
    h_not_defined = _hint(t, "hint_not_defined", "hint_wrong_size")
    h_wrong_type  = _hint(t, "hint_wrong_type",  "hint_wrong_size")
    h_wrong_size  = _hint(t, "hint_wrong_size")
    h_nans        = _hint(t, "hint_nans",        "hint_tolerance")
    h_tolerance   = _hint(t, "hint_tolerance")
    image_md      = t.get("hint_image_md")
    image_md_repr = repr(image_md) if image_md else None

    method_name = f"test_{index:04d}_{name}"

    lines = []
    lines.append(f"    @weight({score!r})")
    lines.append(f"    @number({name!r})")
    lines.append(f"    def {method_name}(self):")
    lines.append(f"        {description!r}")
    lines.extend(_get_result_lines(t, name, h_not_defined))

    lines.append(f"        expected = {_expected_expr(t)}")
    lines.append(f"        status, message = compare(result, expected, {rtol!r}, {atol!r})")
    lines.append('        if status == "wrong_type":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_wrong_type))})")
    lines.append('        elif status == "wrong_size":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_wrong_size))})")
    lines.append('        elif status == "nans":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_nans), image_md_repr)})")
    lines.append('        elif status == "tolerance":')
    lines.append(f"            self.fail(message + {_hint_suffix_expr(repr(h_tolerance), image_md_repr)})")
    lines.append("")
    return "\n".join(lines)


def generate_test_file(test_suite):
    methods = [_generate_test_method(t, i) for i, t in enumerate(test_suite)]
    if not methods:
        methods.append("    pass")
    return HEADER + "\n".join(methods) + "\n"
